name: Run Selenium Test
on:
  push:
    branches: ["master"]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-java@v3
        with:
          java-version: "11"
          cache: maven
          distribution: 'temurin'
      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test
